#!/bin/bash

MAINFOLDER="${HOME}/.config/Internet-Radio"
CONFIG="${MAINFOLDER}/config"

if [ $# -eq 0 ]
then
    if [ ! -d $MAINFOLDER ]
    then
        mkdir -p $MAINFOLDER
        touch ${CONFIG}
    fi
    if [ ! -f $CONFIG ]
    then
        touch $CONFIG
    fi
fi

if [ $# -eq 0 ]
then
    echo "stop"
    cat $CONFIG | cut -d '|' -f2

else
    if [ x"$@" = x"stop" ]
    then
        if [ -f $HOME/.config/Internet-Radio/pid ]
        then
            kill $( cat $HOME/.config/Internet-Radio/pid )
            echo '' > $HOME/.config/Internet-Radio/pid
        fi
    fi
    LINK=$( grep "$@" $CONFIG | head -1 | cut -d '|' -f1 )
    coproc player ( nohup mpv --no-video $LINK > /dev/null 2>&1 ) &&
    echo ${player_PID} > $HOME/pid
    if [ -f $HOME/.config/Internet-Radio/pid ]
    then
        kill $( cat $HOME/.config/Internet-Radio/pid )
    fi
    cat $HOME/pid > $HOME/.config/Internet-Radio/pid
    rm $HOME/pid
fi
